server:
  servlet:
    context-path: /api
  port: 8080


spring:
  sql:
    init:
      schema-locations: classpath:db/quartz_tables_h2.sql

  h2:
    console:
      enabled: true



  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    org:
      hibernate:
        SQL: debug
